### ISSUE TITLE
오늘 설치했는데 처음에 에러 한 번 떠서 올려봅니다.

### ISSUE THREAD

**Issue by creeras** [OrangeDayCom/rhymix-layout#1]
서버 환경은 
- [Basic Information]
- rhymix_version : 2.1.16
- date : 2024-06-25 17:35:46 +0900 (2024-06-25 08:35:46 UTC)
- php : 8.3.8 (64-bit)
- server : nginx/1.18.0
- os : Linux 6.5.0-1020-aws
- sapi : fpm-fcgi
- basedir : /home/xe/

오렌지 1.0.3 설치했구요.
- 레이아웃 
- 게시판 스킨  
적용했습니다. 

게시판이 웹진형이었나? 그랬던 것 같구요. 

에러 내용 (web)
TypeError #0 "in_array(): Argument #2 ($haystack) must be of type array, string given" in modules/board/skins/OrangeDay_board/_comment_write.html on line 70

에러 내용 (console)
2024/06/25 16:55:23 [error] 181219#181219: *537646 FastCGI sent in stderr: "PHP message: PHP Exception: TypeError #0 "in_array(): Argument #2 ($ha
ystack) must be of type array, string given" in modules/board/skins/OrangeDay_board/_comment_write.html on line 70
#0 /home/xe/files/cache/template/modules/board/skins/OrangeDay_board/_comment_write.html.compiled.php(70): in_array()
#1 /home/xe/common/framework/Template.php(471): include()
#2 /home/xe/common/framework/Template.php(375): Rhymix\Framework\Template->execute()
#3 /home/xe/files/cache/template/modules/board/skins/OrangeDay_board/_read_normal.html.compiled.php(36): Rhymix\Framework\Template->compile()
#4 /home/xe/common/framework/Template.php(471): include()
#5 /home/xe/common/framework/Template.php(375): Rhymix\Framework\Template->execute()
#6 /home/xe/files/cache/template/modules/board/skins/OrangeDay_board/read.html.compiled.php(82): Rhymix\Framework\Template->compile()
#7 /home/xe/common/framework/Template.php(471): include()
#8 /home/xe/common/framework/Template.php(375): Rhymix\Framework\Template->execute()
#9 /" while reading response header from upstream, client: 183.105.205.197, server: allcalc.org, request: "GET /board_free2015/42310 HTTP/2.0", up
stream: "fastcgi://unix:/var/run/php/php8.3-fpm.sock:", host: "allcalc.org", referrer: "https://allcalc.org/board_free2015"

에러 코드 
<input type="checkbox" name="notify_message" value="Y" id="notify_message" checked="checked"|cond="@in_array('notify',$mi->wrt_opt ?: [])" />

chatgpt 에게 추천받은 
수정 코드
<input type="checkbox" name="notify_message" value="Y" id="notify_message" checked="checked" |cond="@in_array('notify', is_array($mi->wrt_opt) ? $mi->wrt_opt : [])" />

문제는 해결되었습니다.

**Comment by OrangeDayCom** [comment]
제보 감사드립니다.

해당 태그는 대댓글 관련 소스인데
현재 저는 에러가 발생하지 않아서 재현이 어렵네요.
해당 내용은 지속적으로 살펴볼께요.
