### ISSUE TITLE
메인 페이지(메인 사용중)에서 로그인/회원정보/쪽지함 클릭시 바로 안보이는 문제

### ISSUE THREAD

**Issue by creeras** [OrangeDayCom/rhymix-layout#2]
![스크린샷 2024-06-25 185832](https://github.com/OrangeDayCom/rhymix-layout/assets/4322821/4b6cf01b-fcd4-4113-b97c-1d4747af2311)

[메인] 사용하면 메인 페이지를 (보통은 가득) 채우게 되는데요. 
이 때, 

비로그인 상태로 -- 로그인 누르거나 
비로그인 상태로 -- 가입버튼 누르거나
로그인 상태로 -- 회원 정보 누르거나
로그인 상태로 -- 쪽지함 누르면...

새로 떠야할 창이 [메인] 하단에 붙게 됩니다. 
그래서 원하는 페이지로 이미 이동한 것을 (스크롤바를 내리기 전까지) 알 수가 없습니다. 

이미 한 번 클릭을 했는데 
스크롤을 또 한번 내려야 하는 것도 이상하구요. 

1. 메인 페이지에서 --> 이들 페이지를 이동 하는게 맞는 듯 하구요. 
2. [메인] 페이지에서 붙여야 한다면, 이들을 상단에 놓고, [메인]을 하단에 놓는게 좋을 듯 하구요. 
3. 1.2. 둘 다 안되면, 해당 페이지가 뜰 때 거기로 자동 스크롤 되게 해 주시면 좋을 것 같습니다. 

[수정] 사이트는 https://www.allcalc.org 입니다.

**Comment by OrangeDayCom** [comment]
문의 주신 
--
비로그인 상태로 -- 로그인 누르거나
비로그인 상태로 -- 가입버튼 누르거나
로그인 상태로 -- 회원 정보 누르거나
로그인 상태로 -- 쪽지함 누르면...
--
모두 독립적으로 열립니다.
![image](https://github.com/OrangeDayCom/rhymix-layout/assets/155626754/aa8e7094-2fd8-4fcb-ad98-a510d2852cdb)
![image](https://github.com/OrangeDayCom/rhymix-layout/assets/155626754/4e53e629-f998-4d6e-b431-4a3cccbaca3a)
![image](https://github.com/OrangeDayCom/rhymix-layout/assets/155626754/adc1ed4b-8b90-4048-a654-7173e99dd04b)
![image](https://github.com/OrangeDayCom/rhymix-layout/assets/155626754/03d14588-001e-4876-bd90-a722e2fdae48)

다른거라곤. /xe/폴더에 설치하신건데.. 요건 확인해 봐야 겠네요.

**Comment by creeras** [comment]
![image](https://github.com/OrangeDayCom/rhymix-layout/assets/4322821/76e9def8-bd5e-45e4-9f42-9464912e004a)
회원 정보 중에서도 잘 되는게 있고, 안되는게 있고 하더니 
찾아보니 모듈별로 스킨 설정이 다 따로 있네요. 

지정하니까 잘 됩니다. 
감사합니다.
