### ISSUE TITLE
댓글에 이미지를 왕창 때려박았더니, 수정 버튼이 밀려서 보이질 않습니다.

### ISSUE THREAD

**Issue by creeras** [OrangeDayCom/rhymix-layout#4]
![스크린샷 2024-06-26 161514](https://github.com/OrangeDayCom/rhymix-layout/assets/4322821/a84772e1-395e-4111-8df5-606a6c9a45d0)

**Comment by creeras** [comment]
https://github.com/OrangeDayCom/rhymix-layout/blob/66e160b84fb2e0a0678492e55b5965f6b5c95c1d/1.0.3/modules/board/skins/OrangeDay_board/css/default.css#L798

여기를 바꾸니 해결되는 듯 합니다.
.comListSub li.comCon .fileList {display: flex;justify-content: flex-end;flex-wrap: wrap;}

**Comment by OrangeDayCom** [comment]
다음 버전에서는 아래와 같이
![image](https://github.com/OrangeDayCom/rhymix-layout/assets/155626754/0031698a-bf66-4af7-bfee-fd8e8f6a8177)
