### ISSUE TITLE
메인 스타일 - 클래식에서 

### ISSUE THREAD

**Issue by creeras** [OrangeDayCom/rhymix-layout#5]
TOP VIEW / TOP SUGGEST / RANDOM

이렇게 나오는데요. 
이건 게시판 설정하는 부분이 따로 없더라구요.

제가 (관리자 전용) 삭제글 모음 게시판이 따로 있는데, 
거기 있는 글이 RANDOM 목록에 표시되더군요.

설정한 적이 없어서 살짝 당황했는데, 
찾아보니 설정할 수 있는 곳이 없어서 더 당황했습니다. ^^

* 그리고 이건 기분 탓일 수도 있는 문제인데요. 
RANDOM 인데, 랜덤같지 않고 봤던 글이 계속 보이는 느낌입니다.  돌려막기처럼.

최신글 게시판을 따라가거나, 
아니면 따로 게시판 설정 항목을 추가해주셨으면 합니다.

**Comment by OrangeDayCom** [comment]
요거 사용해보세요.
[layouts.zip](https://github.com/user-attachments/files/16085992/layouts.zip)
![image](https://github.com/OrangeDayCom/rhymix-layout/assets/155626754/54777408-a746-4781-85fc-ba8e0b09e066)

랜덤은 코드를 자세히 보지는 않았지만 원본 그대로 사용하는 중입니다.
시간 날때 한번 봐 볼께요.

**Comment by OrangeDayCom** [comment]
별도로 만들었다가..
가만히 생각해보니 최신글 따라 가는게 좋겠네요.
좋은 의견 감사합니다.

**Comment by creeras** [comment]
> 별도로 만들었다가.. 가만히 생각해보니 최신글 따라 가는게 좋겠네요. 좋은 의견 감사합니다.

감사합니다. 첨부파일 주신 것 적용해 보니 아주 잘 적 됩니다.
